depth: SERVICE_LEVEL
tracers:
  - name: zipkin
    enabled: true
    className: org.ballerina.tracing.extension.zipkin.OpenTracingExtension
    configuration:
      reporter.hostname: localhost
      reporter.port: 9411

  - name: jaeger
    enabled: true
    className: org.ballerina.tracing.extension.jaeger.OpenTracingExtension
    configuration:
      sampler.type: const
      sampler.param: 1
      reporter.log.spans: true
      reporter.hostname: localhost
      reporter.port: 5775
      reporter.flush.interval.ms: 1000
      reporter.max.buffer.spans: 1000

  - name: datadog
    enabled: true
    className: org.ballerina.tracing.extension.datadog.OpenTracingExtension
    configuration:
      service.name: ballerina-service-1
      writer.type: DDAgentWriter
      agent.host: localhost
      agent.port: 8126
      priority.sampling: false
